### ISSUE TITLE
Cozy globalstep issues

### ISSUE THREAD

**Issue by bell07** [Thomas--S/ts_furniture#4]
i am unhappy with the registered globalstep from cozy mod.
In case ts_furniture.enable_sitting is false, the globalstep should not be registered
In case the cozy mod is enabled, the globalstep should not be registered because of the same functionality

**Comment by Thomas--S** [comment]
Thanks!

I'll add this to my to-do-list.

**Comment by Thomas--S** [comment]
Thanks for your patience, I finally fixed this now.

**Comment by bell07** [comment]
If I use the cozy mod, should I disable sitting?
I think it is beter to check for `minetest.get_modpath('cozy') ~= nil`

**Comment by Thomas--S** [comment]
This mod uses a slightly modified (if I remember correctly) version of cozy. There should be no conflicts when using cozy and ts_furniture with sitting enabled at the same time.
